version: 2
jobs:
  test:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run:
          name: test
          command: dotnet test Tmpps.Infrastructure.Template.Tests
  publish:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run:
          name: build
          command: dotnet build -c Release Tmpps.Infrastructure.Template
      - run:
          name: pack
          command: dotnet pack -c Release --include-source -p:PackageVersion=${CIRCLE_TAG} Tmpps.Infrastructure.Template
      - run:
          name: pack
          command: dotnet nuget push ./Tmpps.Infrastructure.Template/bin/Release/Tmpps.Infrastructure.Template.${CIRCLE_TAG}.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          context: nuget-publish
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
